# Header
menu:
  首页: /
  休闲小游戏: /games
  友链: /links
  关于: /about

# 主页banner图
banner: /banner.jpg

# 站点通知信息
notice: 联系我可以发邮件到nickid2018@outlook.com

# 作者信息
author:
  name: Nickid2018
  avatar: /avatar.jpg
  description: 

toc:
  max_depth: 4 # 生成 TOC 的最大深度
  min_depth: 2 # 生成 TOC 的最小深度

comments:
  enable: true
  use: 'valine' # valine || disqus
  # valine 评论
  # docs: https://valine.js.org
  # You can get your appid and appkey from https://leancloud.cn
  # 这里appId和appKey一定一定要改成自己的，没有的话去https://leancloud.cn这个网站注册创建一个
  valine:
    appId: mW2DHhwzDNYk9Gk1hsi4XJV7-gzGzoHsz
    appKey: reCUh7XTXRmlDsR3YfbjreRb
    avatar: mp
    placeholder: 发一条友善的评论吧~~
    notify: true
    visitor: true
    pageSize: 10
  # disqus 评论
  # docs: https://disqus.com/
  disqus:
    website: https://disqus.com/by/nickid2018
    error: 如果你看不到评论，那么就真的看不到评论 w(゜Д゜)w

# dplayer 视频播放
# docs: http://dplayer.js.org/#/zh-Hans/
dplayer:
  enable: true
  theme: "#b7daff"
  autoplay: false
  loop: false
  mutex: true

# aplayer 音频播放
# docs: https://aplayer.js.org/#/zh-Hans/
aplayer:
  enable: true
  theme: "#b7daff"
  autoplay: false
  loop: false
  mutex: true
  lrcType: 3

# 国内备案信息
beian: 

# 谷歌分析
google_analytics: 
# gauges分析
gauges_analytics: 
# 百度分析
baidu_analytics: f32d0139ad5f3b55317728550c14d428
# 腾讯分析
tencent_analytics: 
# 站点ico
favicon: /favicon.ico


# Social Icon
social_icon:
  enable: true
  icons:
    ins      :
    zhihu    :
    weibo    : 
    github   : https://github.com/Nickid2018/
    twitter  : https://twitter.com/Nickid2018/
    bilibili : https://space.bilibili.com/443879411/